local vector = require("scripts/vector")
local vector4 = require("scripts/vector4")

local purple = vector4.new(200, 122, 255, 255)
local blue = vector4.new(0, 121, 241, 255)
local green = vector4.new(0, 228, 48, 255)
local red = vector4.new(230, 41, 55, 255)

local raywhite = vector4.new( 245, 245, 245, 255)

local fontSize = 10

-- TITLE BUTTONS -- 
local startGame = scene.CreateEntity()
local data = vector4.new(g_screenWidth/2, g_screenHeight - g_screenHeight/4, 200, 50)
data.x = data.x - data.z/2
local textData = vector.new(data.x + data.z/4, data.y + data.w/4, 25)
scene.SetComponent(startGame, "button", 0, data)
scene.SetComponent(startGame, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(startGame, "statebutton", 1)
scene.SetComponent(startGame, "text", "GAME", textData)
scene.SetComponent(startGame, "colordata", raywhite)

local editor = scene.CreateEntity()
local data2 = vector4.new(g_screenWidth/2, g_screenHeight - g_screenHeight/4 + 50, 200, 50)
data2.x = data2.x - data2.z/2
local textData2 = vector.new(data2.x + data2.z/4, data2.y + data2.w/4, 25)
scene.SetComponent(editor, "button", 0, data2)
scene.SetComponent(editor, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(editor, "statebutton", 3)
scene.SetComponent(editor, "text", "EDITOR", textData2)
scene.SetComponent(editor, "colordata", raywhite)

-- GAMEPLAY BUTTONS -- 

local spawnLong = scene.CreateEntity()
local longData = vector4.new(g_screenWidth-90, 100, 90, 50)
local longText = vector.new(longData.x+longData.w/4, longData.y+longData.w/2, 10)
scene.SetComponent(spawnLong, "button", 1, longData)
scene.SetComponent(spawnLong, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(spawnLong, "spawnbutton", "LongRange")
scene.SetComponent(spawnLong, "text", "SPAWN LONG\nCost: 5", longText)
scene.SetComponent(spawnLong, "colordata", raywhite)

local spawnShort = scene.CreateEntity()
local shortData = vector4.new(g_screenWidth-90, 160, 90, 50)
local shortText= vector.new(shortData.x+shortData.w/4, shortData.y+shortData.w/2, 10)
scene.SetComponent(spawnShort, "button", 1, shortData)
scene.SetComponent(spawnShort, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(spawnShort, "spawnbutton", "ShortRange")
scene.SetComponent(spawnShort, "text", "SPAWN SHORT\nCost: 10", shortText)
scene.SetComponent(spawnShort, "colordata", raywhite)

local remove = scene.CreateEntity()
local removeData = vector4.new(g_screenWidth-90, 220, 90, 50)
local removeText = vector.new(removeData.x+removeData.w/2, removeData.y+removeData.w/2, 10)
scene.SetComponent(remove, "button", 1, removeData)
scene.SetComponent(remove, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(remove, "spawnbutton", "Remove")
scene.SetComponent(remove, "text", "SELL", removeText)
scene.SetComponent(remove, "colordata", raywhite)

-- ENDING BUTTONS -- 
local endingButton1 = scene.CreateEntity()
local data4 = vector4.new(g_screenWidth/2, g_screenHeight - g_screenHeight/4, 200, 50)
data4.x = data4.x - data4.z/2
local textData4 = vector.new(data4.x + data4.z/4, data4.y + data4.w/4, 25)
scene.SetComponent(endingButton1, "button", 2, data4)
scene.SetComponent(endingButton1, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(endingButton1, "statebutton", 0)
scene.SetComponent(endingButton1, "text", "TO TITLE", textData4)
scene.SetComponent(endingButton1, "colordata", raywhite)

-- EDITOR BUTTONS -- 
local editorButton1 = scene.CreateEntity()
local editordata1 = vector4.new(g_screenWidth-50, 0, 50, 50)
local editorTextData1 = vector.new(editordata1.x, editordata1.y+editordata1.w/2, fontSize)
scene.SetComponent(editorButton1, "button", 3, editordata1)
scene.SetComponent(editorButton1, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(editorButton1, "statebutton", 0)
scene.SetComponent(editorButton1, "text", "TO TITLE", editorTextData1)
scene.SetComponent(editorButton1, "colordata", raywhite)

local startPoint = scene.CreateEntity()
local startPointData = vector4.new(g_screenWidth-100, 50, 100, 50)
local startPointText = vector.new(startPointData.x+startPointData.w/4, startPointData.y+startPointData.w/2, fontSize)
scene.SetComponent(startPoint, "button", 3, startPointData)
scene.SetComponent(startPoint, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(startPoint, "spawnbutton", "startPoint")
scene.SetComponent(startPoint, "text", "SET START", startPointText)
scene.SetComponent(startPoint, "colordata", raywhite)

local endPoint = scene.CreateEntity()
local endPointData = vector4.new(g_screenWidth-100, 100, 100, 50)
local endPointText = vector.new(endPointData.x+endPointData.w/4, endPointData.y+endPointData.w/2, fontSize)
scene.SetComponent(endPoint, "button", 3, endPointData)
scene.SetComponent(endPoint, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(endPoint, "spawnbutton", "endPoint")
scene.SetComponent(endPoint, "text", "SET END", endPointText)
scene.SetComponent(endPoint, "colordata", raywhite)

local blocking = scene.CreateEntity()
local blockingData = vector4.new(g_screenWidth-100, 150, 100, 50)
local blockingText = vector.new(blockingData.x+blockingData.w/4, blockingData.y+blockingData.w/2, fontSize)
scene.SetComponent(blocking, "button", 3, blockingData)
scene.SetComponent(blocking, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(blocking, "spawnbutton", "blocking")
scene.SetComponent(blocking, "text", "SET PATH", blockingText)
scene.SetComponent(blocking, "colordata", raywhite)


local build = scene.CreateEntity()
local buildData = vector4.new(g_screenWidth-100, 200, 100, 50)
local buildText = vector.new(buildData.x+buildData.w/4, buildData.y+buildData.w/2, fontSize)
scene.SetComponent(build, "button", 3, buildData)
scene.SetComponent(build, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(build, "spawnbutton", "build")
scene.SetComponent(build, "text", "BUILD PATH", buildText)
scene.SetComponent(build, "colordata", raywhite)

local clear = scene.CreateEntity()
local clearData = vector4.new(g_screenWidth-100, 250, 100, 50)
local clearText = vector.new(clearData.x+clearData.w/4, clearData.y+clearData.w/2, fontSize)
scene.SetComponent(clear, "button", 3, clearData)
scene.SetComponent(clear, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(clear, "spawnbutton", "clear")
scene.SetComponent(clear, "text", "CLEAR", clearText)
scene.SetComponent(clear, "colordata", raywhite)

local save = scene.CreateEntity()
local saveData = vector4.new(g_screenWidth-100, 300, 100, 50)
local saveText = vector.new(saveData.x+saveData.w/4, saveData.y+saveData.w/2, fontSize)
scene.SetComponent(save, "button", 3, saveData)
scene.SetComponent(save, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(save, "spawnbutton", "save")
scene.SetComponent(save, "text", "SAVE LEVEL", saveText)
scene.SetComponent(save, "colordata", raywhite)

local load = scene.CreateEntity()
local loadData = vector4.new(g_screenWidth-100, 350, 100, 50)
local loadText = vector.new(loadData.x+loadData.w/4, loadData.y+loadData.w/2, fontSize)
scene.SetComponent(load, "button", 3, loadData)
scene.SetComponent(load, "behaviour", "scripts/buttonBehaviour.lua")
scene.SetComponent(load, "spawnbutton", "load")
scene.SetComponent(load, "text", "LOAD LEVEL", loadText)
scene.SetComponent(load, "colordata", raywhite)